### ISSUE TITLE
'container-type' is overwritten

### ISSUE THREAD

**Issue by Nagell** [GoogleChromeLabs/container-query-polyfill#25]
My container Class is using:

```css
        container-type: inline-size;
        container-type: style;
```

but if this plugin is active the first instance is always changed to 
```css
        container: inline-size;
```

the plugin is still working somehow, despite it is throwing an error,
but changing `container-type: size` to `contain: size` can cause
some serious problems (and in my case it does).

https://developer.mozilla.org/en-US/docs/Web/CSS/contain

**Comment by surma** [comment]
Can you give me a small reproduction case in a gist or something where the results are different with the polyfill than with native CQs in Chrome Canary or something?

**Comment by Nagell** [comment]
Yup

```css
    .c-features {
                container-type: size;
    }

    @container (min-width: theme('containerQuery.md')) {
        .c-features {
            & > li {
                max-width: 500px;
            }
        }
    }
```
