### ISSUE TITLE
Polyfill conflicting with react-toastify

### ISSUE THREAD

**Issue by Enebz** [GoogleChromeLabs/container-query-polyfill#32]
**Context**
I am trying to use Polyfill in my react project where I also use TailwindCSS.

**Error message**
```
cqfill.js:204 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': '@media only screen and (max-width : 480px) ' is not a valid selector.
    at handleContainerProps (http://localhost:8000/node_modules/.vite/container-query-polyfill.js?v=49cd73bc:208:29)
    at transpileStyleSheet (http://localhost:8000/node_modules/.vite/container-query-polyfill.js?v=49cd73bc:173:7)
    at handleStyleTag (http://localhost:8000/node_modules/.vite/container-query-polyfill.js?v=49cd73bc:511:20)
    at http://localhost:8000/node_modules/.vite/container-query-polyfill.js?v=49cd73bc:525:55
    at NodeList.forEach (<anonymous>)
    at init (http://localhost:8000/node_modules/.vite/container-query-polyfill.js?v=49cd73bc:525:38)
    at http://localhost:8000/node_modules/.vite/container-query-polyfill.js?v=49cd73bc:530:3
```

**Devtools Inspection**
![image](https://user-images.githubusercontent.com/46542339/161048677-c0e521e2-7630-4c7a-aa12-dffb4d7e5242.png)
As you can see the `sheetSrc` conatins react-toastify contents, and it is the entire toastify stylesheet.

**Some react toastify CSS contents**
```css
@media only screen and (max-width : 480px) {
  .Toastify__toast-container {
    width: 100vw;
    padding: 0;
    left: 0;
    margin: 0;
  }
  .Toastify__toast-container--top-left, .Toastify__toast-container--top-center, .Toastify__toast-container--top-right {
    top: 0;
    transform: translateX(0);
  }
  .Toastify__toast-container--bottom-left, .Toastify__toast-container--bottom-center, .Toastify__toast-container--bottom-right {
    bottom: 0;
    transform: translateX(0);
  }
  .Toastify__toast-container--rtl {
    right: 0;
    left: initial;
  }
}

@media only screen and (max-width : 480px) {
  .Toastify__toast {
    margin-bottom: 0;
    border-radius: 0;
  }
}
```

Here is the media queries that are erroring.

How can I ignore the react-toastify CSS file?
