### ISSUE TITLE
Doesn’t work with Cascade Layers

### ISSUE THREAD

**Issue by mbarker84** [GoogleChromeLabs/container-query-polyfill#46]
When using a container query within a cascade layer the polyfill no longer works.

This works:

```css
body {
  container-type: inline-size;
}

@container (inline-size > 100px) {
  p {
    background: yellow;
  }
}
```

This doesn’t:

```css
@layer layer1;

@layer layer1 {
  body {
    container-type: inline-size;
  }
	
  @container (inline-size > 100px) {
    p {
      background: yellow;
     }
  }
}
```

Tested in Firefox. Full demo [here](https://codepen.io/michellebarker/pen/LYdvxNg/c3b1b0c9c0bafab1990e48b82083685f).
