### ISSUE TITLE
Firefox 107 wrongly accused of not supporting :where breaks style rules

### ISSUE THREAD

**Issue by WebMechanic** [GoogleChromeLabs/container-query-polyfill#69]
Hello,

#68 probably means the same thing, but is not very descriptive, so...

I'm using Firefox 107 with **v1.0.1** of the Polyfill

The console logs
> The :where() pseudo-class is not supported by this browser. To use the Container Query Polyfill, you must modify the selectors under your `@container` rules:

listing the rules inside the affected `@container`.

**Firefox does support `:where()` for quit some time.**

As a result of this false assertion, the `@container` is still replace with a `@media all` and all rules inside are applied to the whole document. That's not a very useful fallback.

```css
.wrapper {
  container-type: inline-size;
  container-name: wraps;
  width: 100%;
  resize: horizontal;
  overflow-x: auto;
}
@container wraps (max-width: 800px) {
  p.fu {color:darkred}
  b.ar {color:green}
}
```

If I add the `:not(.container-query-polyfill)` to both selectors as instructed, the container query works.
