### ISSUE TITLE
Support for style queries

### ISSUE THREAD

**Issue by brandonmcconnell** [GoogleChromeLabs/container-query-polyfill#83]
Unless I'm missing it, it appears this polyfill lacks the newer style query definition. This is essential to some of my use cases for container queries.

```css
@container style(font-weight: bold) {
  color: black;
}
```
